### ISSUE TITLE
Б30: Меню при js должно быть вне потока

### ISSUE THREAD

**Issue by firefoxic** [usalkoulia/244003-pink#4]
Если уж взялась реализовывать меню на js, то и из потока его надо вытаскивать при работающем js.
![image](https://user-images.githubusercontent.com/3382798/36077036-9b87c3ea-0f76-11e8-8f83-76f82b73e246.png)

**Comment by usalkoulia** [comment]
В Б30 написано, что меню должно убираться из потока только в случае, если на макете оно не в потоке. В макетах пинка меню вроде как в потоке. Я что-то неправильно поняла?

**Comment by firefoxic** [comment]
Нет, ты всё правильно поняла. Это я с другим макетом спутал. Прости :)
